plugins {
    id 'net.minecraftforge.gradle' version '5.1.+'
}

version = '0.0.1'
group = 'com.symbioteai'
archivesBaseName = 'symbioteai'

java.sourceCompatibility = '17'
java.targetCompatibility = '17'

minecraft {
    mappings channel: 'official', version: '1.20.1'

    runs {
        client {
            workingDirectory project.file('run/client')
            mods {
                symbioteai {
                    source sourceSets.main
                }
            }
        }
        server {
            workingDirectory project.file('run/server')
            mods {
                symbioteai {
                    source sourceSets.main
                }
            }
        }
    }
}

dependencies {
    minecraft 'net.minecraftforge:forge:1.20.1-47.3.0'
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}
